### ISSUE TITLE
Default implementations

### ISSUE THREAD

**Issue by bjorn3** [Diggsey/query_interface#1]
* `str`
    + `Display`
    + `Debug`
* `String`
    + `Display`
    + `Debug`

**Comment by Diggsey** [comment]
I've added a default set of interfaces for various types from `libstd`. I've also implemented a "dynamic" feature for the crate which enables adding additional interfaces to a type at run-time, bypassing the normal coherence rules.

**Comment by bjorn3** [comment]
thanks
