### ISSUE TITLE
unable to check if type has implemented a trait

### ISSUE THREAD

**Issue by 0x8f701** [Diggsey/query_interface#7]
I would like to use this crate for checking if some type has implemented certain trait but it seems impossible.

Is there a way for doing this?

**Comment by Diggsey** [comment]
This crate defines the notion of an "interface" - that is, a trait implementation that is intrinsic to a type (the same as interfaces in eg. Java). You can make any trait implementation an interface of a type simply by declaring it so with the `interfaces!` macro, but it is opt-in.

This crate allows you to dynamically query for the presence of an interface, but it does not allow you to query for a trait that is not an interface for a type. If that is even possible, it would be outside the scope of this crate.
